services:
  receiver:
    build: ./app
    container_name: media-receiver
    ports:
      - "8787:8787"
    volumes:
      - ./data:/data
      - /volume2/EmbyFiles:/EmblyFiles
    environment:
      - MOVIES_DIR=/EmblyFiles/Movies
      - SERIES_DIR=/EmblyFiles/Series
      - QUEUE_FILE=/data/queue.jsonl
    restart: unless-stopped
